---
- name: Check if RabbitMQ repo is already configured
  stat:
    path: "{{ rabbitmq_repo_file }}"
  register: rabbitmq_repofile_result

- name: Download and run RabbitMQ Package Repository Setup script
  shell: |
    curl -LsS "{{ rabbitmq_repo_script_setup_url }}" | bash -s --
  args:
    executable: "/bin/bash"
  when: not rabbitmq_repofile_result.stat.exists

- name: install RabbitMQ
  yum:
    name: "rabbitmq-server{{ rabbitmq_version_specific | ternary ('-' + (rabbitmq_version_specific | string),'-' + (rabbitmq_version | string) + '*') }}"
    state: present
    disablerepo: "{{ rabbitmq_rpm_disable_repo }}"
    enablerepo: "{{ rabbitmq_rpm_enable_repo }}"

- name: restart RabbitMQ
  meta: flush_handlers

- name: ensure RabbitMQ is started and enabled
  systemd:
    name: "rabbitmq-server.service"
    state: "started"
    enabled: "true"

- name: create RabbitMQ virtualhosts
  rabbitmq_vhost:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ rabbitmq_vhosts }}"

- name: create RabbitMQ users
  rabbitmq_user:
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    vhost: "{{ item.vhost }}"
  with_items:
    - "{{ rabbitmq_users }}"

- name: delete RabbitMQ guest user
  rabbitmq_user:
    user: guest
    state: absent
  when: rabbitmq_delete_guest
